sudo: false
language: go
go:
- 1.6
- 1.7
- 1.7.1
- tip
script: make dist
matrix:
  allow_failures:
  - go: tip
deploy:
  provider: releases
  api_key:
    secure: LQXtXY77kAFzZJaRIdf1LJzQ0pt0zcUJ6KZSbRhULWCBYr8M++Arf2x/5E6HEmqGeALc56uLCLZc7+M+3Taon5Fq3A2DJ+k6aI719hP0gOYrgEtisUU43zzp0VeSeUWfhA3oOv75uzmG7MuDdYAVmG1OrK1n4LNraf6DmKyG62NoViXEauS5LW4NY2jheWbn3JddKuZi/Ky+OWMugtdZ5D8RBbx721tg/veIwGR1feZ4O1zRAmFkT1bXb97TbALmSlougEpc4abiRaeknJinhXfeicGFAAfyeFqbtyzcbZ2fDEOaIbdKR4eTkFB5lVL16sl6xYdL3mPgM6ZTyfQBF4PNFQ/SPZMnydCySd54rsaUhy931xGRR+EgSiDnneWwwallry0Vdk+JJI2dOfrJ6KfN6epc7vsGJ9ODp4PQjqDljGmiQ2wwYPMValBRRpfmM9lHqoL14N0aazAJBQNoWaI4qMaHpmTfql+A00IMgNG67UqJ5GggyKnFaWsGUF3cUIDClMqOA2TzdozJyqp3/AlMqCNM1D91Lvx3UGxYrBt9OcTdNh3yHc5A5s3J9xlShjH8JSp6WOd3GN1uRZHwIEsXR0tXxZBPVFL4kqOU866fMhckpiP6T3vmmOtMr7fnmJ4V3R5WKAsilD1wQQy+rsGyVpaRdy/L/9g6tHpTVdE=
  file: 
  - pkg/darwin_amd64.zip
  - pkg/freebsd_386.zip
  - pkg/freebsd_amd64.zip
  - pkg/freebsd_arm.zip
  - pkg/linux_386.zip
  - pkg/linux_amd64.zip
  - pkg/linux_arm.zip
  - pkg/openbsd_386.zip
  - pkg/openbsd_amd64.zip
  - pkg/solaris_amd64.zip
  - pkg/windows_386.zip
  - pkg/windows_amd64.zip
  on:
    tags: true
notifications:
  slack:
    secure: WQ1v6XL0he7nxhYUoXMCmQ7mxeSNQsz54z+yVw0LhDDIoWuhPmucV9es/yjTrebe7ZfrM8bmxYLxVVKgphQiXmZx/T76z3zZLNv/BfisLQeT2h1AVxHZ78UK8D3nTrdHM0rvosDv2dq6hC0WxtAZWEP/mGf3Nk+4dBLr4scddYyatApThCD50g1uX/kFs6a44OQ+NrxHFgWgN3NUkUDMMylhtd1mXmy1UDPlElc5h/tAspnrfOh4LwZeKl7lz1CdNDMJURwx8ZdVY22EvwPZISxCa4X6oYpoRoXt2zJ/JJE+H6ICwbo1nXbR6dMHnaZ0EWqgkIQUpGQixAdrsyBt8ddV+lrl6HzyMJcno7aae68oHyipJ5pv8/qQsbLlMlOPWCMeIXZpnzaE/dDLLy/3MZHUa4AWfv0xIHKJN7bhKz8dxfc8bqy/KHvIbbAAWUUBub2F9SRb4LK265skIZmIOLCgqAtKp3THwmhucJhLX4+Gt5ioCx6Cw/HDLD8g4uqR9eUPpRyLVn/ntEzERNPhqWzaHHesIVb3mNfOW3AtLkKfxtdICX4be5AGuhbvKljiFDyf7X582UrbfmfnV1Tjb8elDl8i9/bXFrrv+XtdFuvp2aioIZp81KX9BMVBXiDfugTVLjvwYuGxbxP75cym7jg1uYsMwvKduouQ+N9BRxE=
